matrix:
  include:
  - language: node_js
    install:
    - npm install grunt-cli grunt grunt-contrib-qunit
    script:
    - grunt test
  - language: python
    python: 2.7
    env: TOXENV=flake8
  - language: python
    python: 2.7
  - language: python
    python: 2.7
    env: TOXENV=ansi2html
  - language: python
    python: 3.6
    env: TOXENV=flake8
  - language: python
    python: 3.6
    env: TOXENV=py36
  - language: python
    python: 3.6
    env: TOXENV=ansi2html
  - language: python
    python: pypy
  - language: python
    python: pypy
    env: TOXENV=ansi2html
  - language: python
    python: pypy3
  - language: python
    python: pypy3
    env: TOXENV=ansi2html
  - language: python
    python: nightly
  - language: python
    python: nightly
    env: TOXENV=ansi2html
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: davehunt
  password:
    secure: QTNaSfTEZnCEINpCfzdOiOPZ1s6co9Fz2cEt5zv/dSZAJCiKNZvvbMzsOsRMQl1MJvp+cSHiuOir46vEGxzh2+FIl+RRSlENqF2G7jGJpfJfukBxYAhSvt9ZLT4UyBbgYz5sv9A4zs+Yo72xAS9eP+zf5bDVaQh0EzudUbb0Mv4=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: pytest-dev/pytest-html
    python: 3.6
    condition: "$TOXENV = py36"
